version: '3'

services:
  web:
    build: .
    command: gunicorn algo_site.wsgi:application -w 4 -k gthread -b 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - 8000

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - .:/app
    depends_on:
      - web