# Generated by Django 4.2.11 on 2024-04-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
